### ISSUE TITLE
Vertaisarviointi / välipalautus 2

### ISSUE THREAD

**Issue by acidmole** [AlluSu/Autotietokanta#1]
Käyttöohjeet olivat hyvin selkeät kuvien kera, siitä plussa!

Ohjelman rakenne on selkeä, looginen ja sen kaikki toiminnallisuudet toimivat kuten pitääkin. Kannattaisiko kuitenkin omien tietojen muokkauksen jälkeen ohjata käyttäjä vaikka etusivulle? Myöskin jättäisin tietoturvan kannalta kirjautumisen epäonnistuttua erikseen kertomatta onko käyttäjätunnus oikein vai ei.

Toteutus on hyvässä vaiheessa, mutta ohjelman rakenteessa isoin puute on mielestäni sen suppeus. Ainoat toiminnot ovat kirjautuminen sekä ilmoituksen jättäminen ja listaaminen. Voisiko saada tilastoja, tarkennettuja hakuja yms?

Ohjelman koodi on kaikki päämoduulissa. Ennen seuraavaa palautusta kehottaisin siirtämään toiminnallisuudet omiksi moduuleikseen. Tämä maksaa lopulta sen vaivan, jonka siihen käyttää.

**Comment by AlluSu** [comment]
Kiitos palautteesta!
