### ISSUE TITLE
Vertaisarvio 22.2 

### ISSUE THREAD

**Issue by jova486** [AlluSu/Autotietokanta#2]
Projekti on hyvällä mallilla!

Ohjelmaa on helppo käyttää ja kaikki toiminnot loogisesti järjestyksessä.  
Erityisesti ilmoituksen jättäminen on tehty vaivattomaksi kun suoraan voi valita kaikki  tarvittavat tiedot.
Kuten mainitsit readme.md:ssä niin haku eikä ilmoituksen muuttaminen toimi. Ilmeisesti jos klikkaa kuvaa jota ei ole saa ikävän virheilmoituksen? 
Muihin ongelmiin en törmännyt. Jos haluat kehittää ulkoasua niin hieman ikävä on että teksti on kiinni vasemmassa reunassa. Olisi mukavampi jos olisi pieni välistys.  
Ominaisuuksia on mielestäni aivan tarpeeksi kun saat haun toimimaan. 
Koodi on siistiä ja sitä on melko helppo seurata. Koska sitä on jo todella paljon ja tuntuu toimivan niin en ehkä suosittele enää isoja muutoksia. Kuitenkin voisi olla eduksi jos koodi olisi jaettu loogisesti toimintojen mukaan. Ulkopuolisen olisi ainakin helpompi saada kuva kokonaisuudesta. Nyt suurin osa koodista on yhdessä tiedostossa. 
Kunhan saat haun ilmoituksen muuttamisen toimimaan niin mielestäni tässä on kaikki mitä pitääkin.

**Comment by AlluSu** [comment]
Kiitos palautteesta!
